name = "lodhaaltero-wakad"
main = "_worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "."

routes = [
  { pattern = "lodhaaltero.newlaunches.in/*", zone_name = "newlaunches.in" }
]

[placement]
mode = "smart"

[env.production]
name = "lodhaaltero-wakad-prod"
