name = "alterowakad"
main = "_worker.js"
compatibility_date = "2026-09-25"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "."

routes = [
  { pattern = "altero.newlaunches.in/*", zone_name = "newlaunches.in" },
  { pattern = "www.altero.newlaunches.in/*", zone_name = "newlaunches.in" }
]

[placement]
mode = "smart"

[env.production]
name = "alterowakad"
